name: pokemon_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  # State Management
  flutter_bloc: ^8.1.2
  bloc_test: ^9.1.1
  # Dependency Injection
  get_it: ^7.6.0
  # UI Utils
  cupertino_icons: ^1.0.2

  # Value Equality
  equatable: ^2.0.5
  # Functional programing 
  dartz: 0.10.1

  # HttpClient
  http: ^0.13.6
  http_interceptor: ^1.0.2
  # Logger
  logger: ^1.3.0
  # Network status
  connectivity_plus: ^4.0.0
  # Enviropment
  flutter_dotenv: ^5.0.2

  # Data Serialization
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.2
  json_annotation: ^4.8.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.4
  freezed: 2.3.4
  flutter_lints: ^2.0.0
  mocktail: 0.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - .env